// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for product 1",
                            Name = "Product 1",
                            Price = 430m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for product 2",
                            Name = "Product 2",
                            Price = 982m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for product 3",
                            Name = "Product 3",
                            Price = 857m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for product 4",
                            Name = "Product 4",
                            Price = 424m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for product 5",
                            Name = "Product 5",
                            Price = 269m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for product 6",
                            Name = "Product 6",
                            Price = 817m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for product 7",
                            Name = "Product 7",
                            Price = 695m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for product 8",
                            Name = "Product 8",
                            Price = 995m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for product 9",
                            Name = "Product 9",
                            Price = 569m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for product 10",
                            Name = "Product 10",
                            Price = 840m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for product 11",
                            Name = "Product 11",
                            Price = 635m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for product 12",
                            Name = "Product 12",
                            Price = 496m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for product 13",
                            Name = "Product 13",
                            Price = 692m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for product 14",
                            Name = "Product 14",
                            Price = 929m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for product 15",
                            Name = "Product 15",
                            Price = 306m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for product 16",
                            Name = "Product 16",
                            Price = 689m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for product 17",
                            Name = "Product 17",
                            Price = 940m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for product 18",
                            Name = "Product 18",
                            Price = 984m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for product 19",
                            Name = "Product 19",
                            Price = 541m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for product 20",
                            Name = "Product 20",
                            Price = 767m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for product 21",
                            Name = "Product 21",
                            Price = 470m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for product 22",
                            Name = "Product 22",
                            Price = 129m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for product 23",
                            Name = "Product 23",
                            Price = 390m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for product 24",
                            Name = "Product 24",
                            Price = 119m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for product 25",
                            Name = "Product 25",
                            Price = 560m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for product 26",
                            Name = "Product 26",
                            Price = 944m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for product 27",
                            Name = "Product 27",
                            Price = 944m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for product 28",
                            Name = "Product 28",
                            Price = 293m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for product 29",
                            Name = "Product 29",
                            Price = 425m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for product 30",
                            Name = "Product 30",
                            Price = 499m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for product 31",
                            Name = "Product 31",
                            Price = 216m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for product 32",
                            Name = "Product 32",
                            Price = 527m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for product 33",
                            Name = "Product 33",
                            Price = 695m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for product 34",
                            Name = "Product 34",
                            Price = 261m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for product 35",
                            Name = "Product 35",
                            Price = 192m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for product 36",
                            Name = "Product 36",
                            Price = 617m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for product 37",
                            Name = "Product 37",
                            Price = 738m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for product 38",
                            Name = "Product 38",
                            Price = 511m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for product 39",
                            Name = "Product 39",
                            Price = 939m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for product 40",
                            Name = "Product 40",
                            Price = 874m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for product 41",
                            Name = "Product 41",
                            Price = 770m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for product 42",
                            Name = "Product 42",
                            Price = 493m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for product 43",
                            Name = "Product 43",
                            Price = 724m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for product 44",
                            Name = "Product 44",
                            Price = 213m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for product 45",
                            Name = "Product 45",
                            Price = 686m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for product 46",
                            Name = "Product 46",
                            Price = 136m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for product 47",
                            Name = "Product 47",
                            Price = 250m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for product 48",
                            Name = "Product 48",
                            Price = 146m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for product 49",
                            Name = "Product 49",
                            Price = 409m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for product 50",
                            Name = "Product 50",
                            Price = 876m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for product 51",
                            Name = "Product 51",
                            Price = 720m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for product 52",
                            Name = "Product 52",
                            Price = 536m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for product 53",
                            Name = "Product 53",
                            Price = 491m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for product 54",
                            Name = "Product 54",
                            Price = 499m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for product 55",
                            Name = "Product 55",
                            Price = 774m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for product 56",
                            Name = "Product 56",
                            Price = 400m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for product 57",
                            Name = "Product 57",
                            Price = 691m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for product 58",
                            Name = "Product 58",
                            Price = 837m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for product 59",
                            Name = "Product 59",
                            Price = 864m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for product 60",
                            Name = "Product 60",
                            Price = 325m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for product 61",
                            Name = "Product 61",
                            Price = 873m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for product 62",
                            Name = "Product 62",
                            Price = 501m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for product 63",
                            Name = "Product 63",
                            Price = 669m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for product 64",
                            Name = "Product 64",
                            Price = 170m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for product 65",
                            Name = "Product 65",
                            Price = 723m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for product 66",
                            Name = "Product 66",
                            Price = 208m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for product 67",
                            Name = "Product 67",
                            Price = 801m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for product 68",
                            Name = "Product 68",
                            Price = 531m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for product 69",
                            Name = "Product 69",
                            Price = 836m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for product 70",
                            Name = "Product 70",
                            Price = 688m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for product 71",
                            Name = "Product 71",
                            Price = 950m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for product 72",
                            Name = "Product 72",
                            Price = 528m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for product 73",
                            Name = "Product 73",
                            Price = 145m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for product 74",
                            Name = "Product 74",
                            Price = 666m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for product 75",
                            Name = "Product 75",
                            Price = 997m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for product 76",
                            Name = "Product 76",
                            Price = 977m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for product 77",
                            Name = "Product 77",
                            Price = 404m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for product 78",
                            Name = "Product 78",
                            Price = 276m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for product 79",
                            Name = "Product 79",
                            Price = 432m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for product 80",
                            Name = "Product 80",
                            Price = 524m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for product 81",
                            Name = "Product 81",
                            Price = 793m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for product 82",
                            Name = "Product 82",
                            Price = 897m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for product 83",
                            Name = "Product 83",
                            Price = 884m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for product 84",
                            Name = "Product 84",
                            Price = 549m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for product 85",
                            Name = "Product 85",
                            Price = 779m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for product 86",
                            Name = "Product 86",
                            Price = 680m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for product 87",
                            Name = "Product 87",
                            Price = 135m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for product 88",
                            Name = "Product 88",
                            Price = 295m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for product 89",
                            Name = "Product 89",
                            Price = 486m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for product 90",
                            Name = "Product 90",
                            Price = 792m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for product 91",
                            Name = "Product 91",
                            Price = 926m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for product 92",
                            Name = "Product 92",
                            Price = 900m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for product 93",
                            Name = "Product 93",
                            Price = 647m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for product 94",
                            Name = "Product 94",
                            Price = 714m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for product 95",
                            Name = "Product 95",
                            Price = 100m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for product 96",
                            Name = "Product 96",
                            Price = 368m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for product 97",
                            Name = "Product 97",
                            Price = 823m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for product 98",
                            Name = "Product 98",
                            Price = 654m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for product 99",
                            Name = "Product 99",
                            Price = 489m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description for product 100",
                            Name = "Product 100",
                            Price = 577m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductStock", b =>
                {
                    b.Property<int>("ProductStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            ProductStockId = 1,
                            ProductId = 1,
                            Stock = 15
                        },
                        new
                        {
                            ProductStockId = 2,
                            ProductId = 2,
                            Stock = 13
                        },
                        new
                        {
                            ProductStockId = 3,
                            ProductId = 3,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 4,
                            ProductId = 4,
                            Stock = 0
                        },
                        new
                        {
                            ProductStockId = 5,
                            ProductId = 5,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 6,
                            ProductId = 6,
                            Stock = 16
                        },
                        new
                        {
                            ProductStockId = 7,
                            ProductId = 7,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 8,
                            ProductId = 8,
                            Stock = 10
                        },
                        new
                        {
                            ProductStockId = 9,
                            ProductId = 9,
                            Stock = 8
                        },
                        new
                        {
                            ProductStockId = 10,
                            ProductId = 10,
                            Stock = 4
                        },
                        new
                        {
                            ProductStockId = 11,
                            ProductId = 11,
                            Stock = 3
                        },
                        new
                        {
                            ProductStockId = 12,
                            ProductId = 12,
                            Stock = 3
                        },
                        new
                        {
                            ProductStockId = 13,
                            ProductId = 13,
                            Stock = 18
                        },
                        new
                        {
                            ProductStockId = 14,
                            ProductId = 14,
                            Stock = 11
                        },
                        new
                        {
                            ProductStockId = 15,
                            ProductId = 15,
                            Stock = 12
                        },
                        new
                        {
                            ProductStockId = 16,
                            ProductId = 16,
                            Stock = 18
                        },
                        new
                        {
                            ProductStockId = 17,
                            ProductId = 17,
                            Stock = 14
                        },
                        new
                        {
                            ProductStockId = 18,
                            ProductId = 18,
                            Stock = 2
                        },
                        new
                        {
                            ProductStockId = 19,
                            ProductId = 19,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 20,
                            ProductId = 20,
                            Stock = 19
                        },
                        new
                        {
                            ProductStockId = 21,
                            ProductId = 21,
                            Stock = 3
                        },
                        new
                        {
                            ProductStockId = 22,
                            ProductId = 22,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 23,
                            ProductId = 23,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 24,
                            ProductId = 24,
                            Stock = 3
                        },
                        new
                        {
                            ProductStockId = 25,
                            ProductId = 25,
                            Stock = 9
                        },
                        new
                        {
                            ProductStockId = 26,
                            ProductId = 26,
                            Stock = 4
                        },
                        new
                        {
                            ProductStockId = 27,
                            ProductId = 27,
                            Stock = 11
                        },
                        new
                        {
                            ProductStockId = 28,
                            ProductId = 28,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 29,
                            ProductId = 29,
                            Stock = 13
                        },
                        new
                        {
                            ProductStockId = 30,
                            ProductId = 30,
                            Stock = 5
                        },
                        new
                        {
                            ProductStockId = 31,
                            ProductId = 31,
                            Stock = 9
                        },
                        new
                        {
                            ProductStockId = 32,
                            ProductId = 32,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 33,
                            ProductId = 33,
                            Stock = 8
                        },
                        new
                        {
                            ProductStockId = 34,
                            ProductId = 34,
                            Stock = 14
                        },
                        new
                        {
                            ProductStockId = 35,
                            ProductId = 35,
                            Stock = 3
                        },
                        new
                        {
                            ProductStockId = 36,
                            ProductId = 36,
                            Stock = 12
                        },
                        new
                        {
                            ProductStockId = 37,
                            ProductId = 37,
                            Stock = 8
                        },
                        new
                        {
                            ProductStockId = 38,
                            ProductId = 38,
                            Stock = 4
                        },
                        new
                        {
                            ProductStockId = 39,
                            ProductId = 39,
                            Stock = 7
                        },
                        new
                        {
                            ProductStockId = 40,
                            ProductId = 40,
                            Stock = 11
                        },
                        new
                        {
                            ProductStockId = 41,
                            ProductId = 41,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 42,
                            ProductId = 42,
                            Stock = 1
                        },
                        new
                        {
                            ProductStockId = 43,
                            ProductId = 43,
                            Stock = 1
                        },
                        new
                        {
                            ProductStockId = 44,
                            ProductId = 44,
                            Stock = 0
                        },
                        new
                        {
                            ProductStockId = 45,
                            ProductId = 45,
                            Stock = 4
                        },
                        new
                        {
                            ProductStockId = 46,
                            ProductId = 46,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 47,
                            ProductId = 47,
                            Stock = 19
                        },
                        new
                        {
                            ProductStockId = 48,
                            ProductId = 48,
                            Stock = 0
                        },
                        new
                        {
                            ProductStockId = 49,
                            ProductId = 49,
                            Stock = 18
                        },
                        new
                        {
                            ProductStockId = 50,
                            ProductId = 50,
                            Stock = 12
                        },
                        new
                        {
                            ProductStockId = 51,
                            ProductId = 51,
                            Stock = 14
                        },
                        new
                        {
                            ProductStockId = 52,
                            ProductId = 52,
                            Stock = 13
                        },
                        new
                        {
                            ProductStockId = 53,
                            ProductId = 53,
                            Stock = 3
                        },
                        new
                        {
                            ProductStockId = 54,
                            ProductId = 54,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 55,
                            ProductId = 55,
                            Stock = 16
                        },
                        new
                        {
                            ProductStockId = 56,
                            ProductId = 56,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 57,
                            ProductId = 57,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 58,
                            ProductId = 58,
                            Stock = 14
                        },
                        new
                        {
                            ProductStockId = 59,
                            ProductId = 59,
                            Stock = 10
                        },
                        new
                        {
                            ProductStockId = 60,
                            ProductId = 60,
                            Stock = 2
                        },
                        new
                        {
                            ProductStockId = 61,
                            ProductId = 61,
                            Stock = 4
                        },
                        new
                        {
                            ProductStockId = 62,
                            ProductId = 62,
                            Stock = 19
                        },
                        new
                        {
                            ProductStockId = 63,
                            ProductId = 63,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 64,
                            ProductId = 64,
                            Stock = 3
                        },
                        new
                        {
                            ProductStockId = 65,
                            ProductId = 65,
                            Stock = 14
                        },
                        new
                        {
                            ProductStockId = 66,
                            ProductId = 66,
                            Stock = 16
                        },
                        new
                        {
                            ProductStockId = 67,
                            ProductId = 67,
                            Stock = 15
                        },
                        new
                        {
                            ProductStockId = 68,
                            ProductId = 68,
                            Stock = 4
                        },
                        new
                        {
                            ProductStockId = 69,
                            ProductId = 69,
                            Stock = 7
                        },
                        new
                        {
                            ProductStockId = 70,
                            ProductId = 70,
                            Stock = 0
                        },
                        new
                        {
                            ProductStockId = 71,
                            ProductId = 71,
                            Stock = 9
                        },
                        new
                        {
                            ProductStockId = 72,
                            ProductId = 72,
                            Stock = 10
                        },
                        new
                        {
                            ProductStockId = 73,
                            ProductId = 73,
                            Stock = 14
                        },
                        new
                        {
                            ProductStockId = 74,
                            ProductId = 74,
                            Stock = 15
                        },
                        new
                        {
                            ProductStockId = 75,
                            ProductId = 75,
                            Stock = 13
                        },
                        new
                        {
                            ProductStockId = 76,
                            ProductId = 76,
                            Stock = 2
                        },
                        new
                        {
                            ProductStockId = 77,
                            ProductId = 77,
                            Stock = 16
                        },
                        new
                        {
                            ProductStockId = 78,
                            ProductId = 78,
                            Stock = 5
                        },
                        new
                        {
                            ProductStockId = 79,
                            ProductId = 79,
                            Stock = 19
                        },
                        new
                        {
                            ProductStockId = 80,
                            ProductId = 80,
                            Stock = 12
                        },
                        new
                        {
                            ProductStockId = 81,
                            ProductId = 81,
                            Stock = 4
                        },
                        new
                        {
                            ProductStockId = 82,
                            ProductId = 82,
                            Stock = 10
                        },
                        new
                        {
                            ProductStockId = 83,
                            ProductId = 83,
                            Stock = 18
                        },
                        new
                        {
                            ProductStockId = 84,
                            ProductId = 84,
                            Stock = 1
                        },
                        new
                        {
                            ProductStockId = 85,
                            ProductId = 85,
                            Stock = 10
                        },
                        new
                        {
                            ProductStockId = 86,
                            ProductId = 86,
                            Stock = 16
                        },
                        new
                        {
                            ProductStockId = 87,
                            ProductId = 87,
                            Stock = 3
                        },
                        new
                        {
                            ProductStockId = 88,
                            ProductId = 88,
                            Stock = 1
                        },
                        new
                        {
                            ProductStockId = 89,
                            ProductId = 89,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 90,
                            ProductId = 90,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 91,
                            ProductId = 91,
                            Stock = 5
                        },
                        new
                        {
                            ProductStockId = 92,
                            ProductId = 92,
                            Stock = 14
                        },
                        new
                        {
                            ProductStockId = 93,
                            ProductId = 93,
                            Stock = 13
                        },
                        new
                        {
                            ProductStockId = 94,
                            ProductId = 94,
                            Stock = 5
                        },
                        new
                        {
                            ProductStockId = 95,
                            ProductId = 95,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 96,
                            ProductId = 96,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 97,
                            ProductId = 97,
                            Stock = 4
                        },
                        new
                        {
                            ProductStockId = 98,
                            ProductId = 98,
                            Stock = 17
                        },
                        new
                        {
                            ProductStockId = 99,
                            ProductId = 99,
                            Stock = 6
                        },
                        new
                        {
                            ProductStockId = 100,
                            ProductId = 100,
                            Stock = 8
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
